# Generated by Django 4.2.3 on 2024-03-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_privacypolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=200)),
                ('ownerName', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phoneNo', models.PositiveBigIntegerField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
