# Generated by Django 4.2.3 on 2025-04-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='phoneNO',
            new_name='phoneNo',
        ),
    ]
