# Generated by Django 5.0.2 on 2024-02-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activate',
            field=models.BooleanField(default=False),
        ),
    ]
