# Generated by Django 4.2.3 on 2024-03-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sub_admin',
            field=models.BooleanField(default=False),
        ),
    ]
