# Generated by Django 5.0.2 on 2024-02-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='nepali_date',
            field=models.CharField(blank=True, default='09-Falgun-2080', max_length=50, null=True),
        ),
    ]
