# Generated by Django 5.0.2 on 2024-02-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_daily_nepali_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='nepali_date',
            field=models.CharField(default='09-Falgun-2080', max_length=50),
        ),
    ]
