# Generated by Django 4.2.3 on 2025-05-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_alter_daily_nepali_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='nepali_date',
            field=models.CharField(default='19-Baishakh-2082', max_length=50),
        ),
    ]
