# Generated by Django 4.2.3 on 2024-03-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick_up_plan',
            name='date',
            field=models.CharField(default='21-Falgun-2080', max_length=50),
        ),
    ]
