# Generated by Django 5.0.2 on 2024-02-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_orderaddress_alternativeno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestaddress',
            name='fullname',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestaddress',
            name='landmark',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestaddress',
            name='location',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestaddress',
            name='phoneNumber',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
