# Generated by Django 5.0.2 on 2024-02-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_requestaddress_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestaddress',
            name='landmark',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
