# Generated by Django 5.0.2 on 2024-02-15 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_requestaddress_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_address', to='order.requestaddress'),
        ),
        migrations.DeleteModel(
            name='OrderAddress',
        ),
    ]
