# Generated by Django 5.0.2 on 2024-02-18 09:07

import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default=order.models.generate_invoice_number, editable=False, max_length=4, unique=True),
        ),
    ]
