# Generated by Django 4.2.3 on 2024-03-06 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_created_alter_pick_up_plan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_address', to='order.requestaddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.CharField(default='23-Falgun-2080', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='pick_up_plan',
            name='date',
            field=models.CharField(default='23-Falgun-2080', max_length=50),
        ),
    ]
