# Generated by Django 5.0.2 on 2024-02-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='note',
            field=models.TextField(default='All accounts are to be paid within 7 days from receipt of invoice. To be paid by cheque or credit card or direct payment online or cash. If account is not paid within 7 days the credits details supplied as confirmation of work undertaken will be charged the agreed quoted fee noted above.'),
        ),
    ]
