# Generated by Django 5.0.2 on 2024-02-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_invoice_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='note',
            field=models.TextField(),
        ),
    ]
