# Generated by Django 4.2.3 on 2024-03-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_address_alter_order_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.CharField(default='29-Falgun-2080', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='pick_up_plan',
            name='date',
            field=models.CharField(default='29-Falgun-2080', max_length=50),
        ),
    ]
