# Generated by Django 5.0.2 on 2024-02-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_invoice_summery_invoice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_statu',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=50),
        ),
    ]
