# Generated by Django 5.0.2 on 2024-02-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_pick_up_plan_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick_up_plan',
            name='date',
            field=models.CharField(default='09-Falgun-2080', max_length=50),
        ),
    ]
