# Generated by Django 4.2.3 on 2024-04-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_notification_options_notification_order_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.CharField(default='20-Chaitra-2080', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='pick_up_plan',
            name='date',
            field=models.CharField(default='20-Chaitra-2080', max_length=50),
        ),
    ]
