# Generated by Django 4.2.3 on 2025-03-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_order_created_alter_pick_up_plan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.CharField(default='20-Falgun-2081', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='pick_up_plan',
            name='date',
            field=models.CharField(default='20-Falgun-2081', max_length=50),
        ),
    ]
