# Generated by Django 4.2.3 on 2025-03-05 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_alter_order_created_alter_pick_up_plan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestaddress',
            name='phoneNumber',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('\\d{3}?-?\\d{3}?-?\\d{4}', 'Only ten numbers and dashes allowed.')]),
        ),
    ]
