# Generated by Django 4.2.3 on 2025-04-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_order_order_status_changed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.CharField(default='13-Baishakh-2082', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='pick_up_plan',
            name='date',
            field=models.CharField(default='13-Baishakh-2082', max_length=50),
        ),
    ]
