# Generated by Django 4.2.3 on 2025-04-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_order_created_alter_pick_up_plan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order', 'Order'), ('system', 'System')], default='order', max_length=50),
        ),
    ]
