# Generated by Django 4.2.3 on 2025-05-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_alter_order_created_alter_pick_up_plan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='system_notification_image/'),
        ),
    ]
