# Generated by Django 4.2.3 on 2025-05-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_alter_notification_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='image',
            field=models.ImageField(upload_to='system_notification_image/'),
        ),
    ]
