# Generated by Django 4.2.3 on 2025-05-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_alter_notification_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='system_notification_image/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
