# Generated by Django 4.2.3 on 2024-03-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_invoice_item_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='type',
        ),
        migrations.AddField(
            model_name='stock',
            name='sold_quantity',
            field=models.FloatField(default=0),
        ),
    ]
