# Generated by Django 4.2.3 on 2024-03-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_stock_type_stock_sold_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='date_updated',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
