# Generated by Django 4.2.3 on 2024-03-04 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_invoice_date_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_item',
            name='stock',
        ),
    ]
