# Generated by Django 4.2.3 on 2024-03-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_invoice_item_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.CharField(default='21-Falgun-2080', max_length=50),
        ),
    ]
