# Generated by Django 4.2.3 on 2024-03-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_invoice_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_created',
            field=models.CharField(default='21-Falgun-2080', max_length=50),
        ),
    ]
