# Generated by Django 4.2.3 on 2024-03-04 10:04

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_invoice_options_alter_stock_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='transaction',
            field=models.CharField(default=products.models.generate_transaction_id, editable=False, max_length=250),
        ),
    ]
