# Generated by Django 4.2.3 on 2024-03-18 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_customers'),
        ('products', '0015_alter_invoice_date_created_alter_stock_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customers', to='app2.customers'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.CharField(default='05-Chaitra-2080', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_created',
            field=models.CharField(default='05-Chaitra-2080', max_length=50),
        ),
    ]
