# Generated by Django 4.2.3 on 2024-03-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_invoice_customer_alter_invoice_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.CharField(default='06-Chaitra-2080', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_created',
            field=models.CharField(default='06-Chaitra-2080', max_length=50),
        ),
    ]
