# Generated by Django 4.2.3 on 2024-04-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_invoice_date_created_alter_stock_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='previous_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.CharField(default='20-Chaitra-2080', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_created',
            field=models.CharField(default='20-Chaitra-2080', max_length=50),
        ),
    ]
