# Generated by Django 4.2.3 on 2024-05-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_previous_rate_alter_invoice_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.CharField(default='20-Baishakh-2081', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_created',
            field=models.CharField(default='20-Baishakh-2081', max_length=50),
        ),
    ]
