# Generated by Django 4.2.3 on 2025-03-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_order_number_alter_invoice_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order_number']},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.CharField(default='20-Falgun-2081', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_created',
            field=models.CharField(default='20-Falgun-2081', max_length=50),
        ),
    ]
