# Generated by Django 4.2.3 on 2025-03-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_options_alter_invoice_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.CharField(default='21-Falgun-2081', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_created',
            field=models.CharField(default='21-Falgun-2081', max_length=50),
        ),
    ]
