# Generated by Django 4.2.3 on 2025-04-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_invoice_date_created_alter_stock_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.CharField(default='13-Baishakh-2082', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_created',
            field=models.CharField(default='13-Baishakh-2082', max_length=50),
        ),
    ]
